package com.jpaAndActivity.domain;

import java.io.Serializable;

// Generated by Hibernate Tools

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RoleInfo .
 *
 * @author Lingo
 */
@Entity
@Table(name = "ROLE_INFO")
public class RoleInfo implements Serializable {

	private static final long serialVersionUID = 1L;
	/** null. */
	private Long id;
	/** null. */
	private String code;
	/** null. */
	private String name;
	/** null. */
	private String descn;
	/** null. */
	private Date createTime;
	/** . */
	private Set<UserInfo> userInfos = new HashSet<UserInfo>(0);
	/** . */
	private Set<MenuInfo> menuInfos = new HashSet<MenuInfo>(0);

	public RoleInfo() {
	}

	public RoleInfo(Long id) {
		this.id = id;
	}

	public RoleInfo(Long id, String code, String name, String descn, Date createTime, Set<UserInfo> userInfos,
			Set<MenuInfo> menuInfos) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.descn = descn;
		this.createTime = createTime;
		this.userInfos = userInfos;
		this.menuInfos = menuInfos;
	}

	/** @return null. */
	@Id

	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	/**
	 * @param id
	 *            null.
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/** @return null. */

	@Column(name = "CODE", length = 50)
	public String getCode() {
		return this.code;
	}

	/**
	 * @param code
	 *            null.
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/** @return null. */

	@Column(name = "NAME", length = 50)
	public String getName() {
		return this.name;
	}

	/**
	 * @param name
	 *            null.
	 */
	public void setName(String name) {
		this.name = name;
	}

	/** @return null. */

	@Column(name = "DESCN", length = 200)
	public String getDescn() {
		return this.descn;
	}

	/**
	 * @param descn
	 *            null.
	 */
	public void setDescn(String descn) {
		this.descn = descn;
	}

	/** @return null. */

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATE_TIME", length = 26)
	public Date getCreateTime() {
		return this.createTime;
	}

	/**
	 * @param createTime
	 *            null.
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/** @return . */

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "USER_ROLE", joinColumns = {
			@JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "USER_ID", nullable = false, updatable = false) })
	public Set<UserInfo> getUserInfos() {
		return this.userInfos;
	}

	/**
	 * @param userInfos
	 *            .
	 */
	public void setUserInfos(Set<UserInfo> userInfos) {
		this.userInfos = userInfos;
	}

	/** @return . */

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "ROLE_MENU", joinColumns = {
			@JoinColumn(name = "ROLE_ID", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "MENU_ID", nullable = false, updatable = false) })
	public Set<MenuInfo> getMenuInfos() {
		return this.menuInfos;
	}

	/**
	 * @param menuInfos
	 *            .
	 */
	public void setMenuInfos(Set<MenuInfo> menuInfos) {
		this.menuInfos = menuInfos;
	}

}
